Fix a NoSuchMethodError when running code compiled by JDK 9 on JDK 8
Java 9 introduces overridden methods with covariant return types for
the chain-able methods in java.nio.ByteBuffer.

The generated byte code includes the static return type of the method,
which isn't found on JDK8 and lower because the overloaded methods with
covariant return types don't exist.